### ISSUE TITLE
Support node < 18

### ISSUE THREAD

**Issue by Snipon** [Relewise/relewise-sdk-javascript#8]
Right now it's using native fetch. It would be nice to support LTS, since many frameworks rely on that release cycle.

**Comment by mzanoni** [comment]
We can look into that, we are requiring node 18 because our CDN minified file went from 400kb to 3 kb by moving from node 16 to node 18 without having to rely on any 3rd party dependencies.

**Comment by mzanoni** [comment]
@Snipon 

This will be resolved here: https://github.com/Relewise/relewise-sdk-javascript/pull/9
